### ISSUE TITLE
Showing Serbian language in subtitles results, crashes kodi

### ISSUE THREAD

**Issue by GnFlala** [jester-xbmc/skin.amber#10]
error in logs is 
ERROR: Texture manager unable to load bundled file: flags/sr.gif

Weird part is that the flag gifs are completly missing if you install from within kodi, while they are there in github files.

Replicated in windows, osx, rpi with osmc.

Please tell me if you need full logs.

**Comment by jester-xbmc** [comment]
Can you remove the textures file and replace it with https://github.com/jester-xbmc/skin.amber/tree/master/media 
and see if you can replicate the problem?, I will have a look over the weekend, it might be a missing/corrupted sr.gif in the texture file on the official repo

**Comment by GnFlala** [comment]
Ofc i can please allow me with a delay of 1 hour since i am still at work.

Also i hope its not a mistake reporting something here. If it is i am really sorry.

And last do not forget that if you install amber from within kodi, the folder media/flags is almost empty while from github it is not. I do not know if that helps.

**Comment by jester-xbmc** [comment]
Don't worry, if its a mistake we close it ;-)

you have to remove the amber skin that is installed from the official kodi repo and replace it with the one from github.
(its correct that media/ is almost empty, all the files are in a sort of zip file called texures)

**Comment by GnFlala** [comment]
Really sorry for the delay sir.

That does the trick.

I did not only replace the flags folder witht he one from github but also replaced the DialogSubtitles.xml since i saw you made changes the same time.

Solved.

Do you need anything else to see like a log file?
Anything else i can do from my side?

**Comment by jester-xbmc** [comment]
Dont worry about it, i'm glad its fixed, i'll close the issue and I will push this release to the official kodi repo for Isengard
Thanks for testing.
