### ISSUE TITLE
watched marks / unwatched marks not working correctly

### ISSUE THREAD

**Issue by jester-xbmc** [jester-xbmc/skin.amber#12]
recently added items (movies) no marks will show up, whatever the settings
random added items (movies) all partially views marks are displayed, not correct, and not hidden if hidden is enabled.

**Comment by joethepartylion** [comment]
Hi Jester, this seems hardcoded into the includes, see Includes_Vertical_Home.xml, Lines 130-136 for example. I'll see If I can get a fix together.

**Comment by jester-xbmc** [comment]
ok, are we sure its not linked to the service.skin.widgets ? as that's used to populate those ?

**Comment by joethepartylion** [comment]
It is in some way, i.e. the overlays have been hardcoded in the include none for recently added, but recommended has the inprogress overlay hardcoded but to make it dynamic we need to use info provided by the service. 

I would rather we user the existing $VAR[Overlay] to fix it but I think this is going to need a extension of the $VAR[Overlay] as the widget uses different infobools\labels i.e. RandomMovie.%d.Resume not listitem.inprogress, and RandomMovie.%d.Watched not ListItem.Overlay. 

I'll see what I can come up with and see if it is possible.

**Comment by joethepartylion** [comment]
OK, so you are right in that we do need to pull info from the skin.widgets. We can maybe hide that in a lable2 for the item and then do a substring compare to see if it is watched\inprogress or not..I'll give it a go.

**Comment by joethepartylion** [comment]
Hopefully fixed in #29.
