### ISSUE TITLE
List view not displaying metadata

### ISSUE THREAD

**Issue by spraddles** [jester-xbmc/skin.amber#14]
This occurs in the following situation:
-go to Videos > Files > Add Videos
-add your source & set the meta type (e.g. Movie)
-let the scraper get all the metadata
-set the new source as a favourite
-add favourite to home menu via Settings > Home Menu
-new source now displays in the home menu

There's no issues with the Movies or TV menu items - except when adding a favourite to the home menu, as above.
![capture](https://cloud.githubusercontent.com/assets/4809356/10423110/af45f9fa-710e-11e5-8346-f6d6a02d853c.PNG)

**Comment by jester-xbmc** [comment]
Thanks for the report, I will have a look

**Comment by joethepartylion** [comment]
Is this still an issue now that the views have been rewritten?

**Comment by jester-xbmc** [comment]
I think its fixed, re-open when its still an issuee
