### ISSUE TITLE
no "Parental locked" option in Channel Manager

### ISSUE THREAD

**Issue by hokuspokuzz** [jester-xbmc/skin.amber#22]
Hi Jester,

There is no option "Parental locked (enable/disable)" in the Channel Manager. This means that the Live TV Parental lock is unfunctional in your skin. You can set a Pin in settings but you can not lock channels.

Is there any way I can quickfix this myself ( via an XML or something?) via ssh/sftp on my own box, instead of waiting for next skin update?

Awesome skin nevertheless. regards !

**Comment by hokuspokuzz** [comment]
i guess i should edit "DialogPVRChannelManager.xml" from the /storage/.kodi/addons/skin.amber/1080i/ path?

Can you tell me what i should add to that xml?

**Comment by hokuspokuzz** [comment]
I applied the following quickfix, which works:

```
    <control type="radiobutton" id="14" description="Parental Locked">
```

However the wiki is not up to date on this, it doesn't state id 14:

http://kodi.wiki/view/List_of_Built_In_Controls#DialogPVRChannelManager.xml

regards

**Comment by jester-xbmc** [comment]
Hi, thanks, if this change works for you (I don't use parental control) please do a pull request for the change.
the wiki is indeed outdated, most of these dialog xml files will soon be merged into one file for Kodi v17

**Comment by jester-xbmc** [comment]
Fixed in https://github.com/jester-xbmc/skin.amber/commit/059a1bcf15b1cd850a0079e3381bde7d59378779
