### ISSUE TITLE
weather info on homescreen bottom overlaps RSS

### ISSUE THREAD

**Issue by ondrejbima** [jester-xbmc/skin.amber#35]
Weather info conflict with RSS feed.
Amber 2.2.3, Horizontal menu

rel @3ba44f3291d677c7a177c6de36391587c5fa99ef

**Comment by beam** [comment]
rel @3ba44f3291d677c7a177c6de36391587c5fa99ef

**Comment by jester-xbmc** [comment]
Thanks, checking...

**Comment by joethepartylion** [comment]
That's my fault, I never use RSS so forgot to check, @jester-xbmc do you want me to take this one as the vertical version has some formatting issues too if the temperature value has more than one digit?
