### ISSUE TITLE
 Favourites icons wrong aspect ratio

### ISSUE THREAD

**Issue by Smultie** [jester-xbmc/skin.amber#4]
Look at Marvel Agents of S.H.I.E.L.D. for reference

TV Shows shows the correct image:
http://imgur.com/YndQsiA

Favourites shows them way wrong:
http://imgur.com/4KGIpXf

**Comment by Smultie** [comment]
?

**Comment by jester-xbmc** [comment]
I will look at this when I have some time, its not high on my list as i'm a horizontal user mainly ;)
