### ISSUE TITLE
Addon shelf items not highliting

### ISSUE THREAD

**Issue by vitalyg149** [jester-xbmc/skin.amber#41]
When choosing addon shelf items they are not highlighted and you cannot see your what you are selecting. This happened after update to 2.2.4
<img width="844" alt="capture" src="https://cloud.githubusercontent.com/assets/17891915/13833415/0b3811c6-ebbc-11e5-9632-1523701bcca7.PNG">

**Comment by joethepartylion** [comment]
Should be fixed in #40

**Comment by jester-xbmc** [comment]
Confirmed fixed in #40, just pulled, will be updated on the official repo later.
Thanks
