### ISSUE TITLE
Incorrect German translations

### ISSUE THREAD

**Issue by joethepartylion** [jester-xbmc/skin.amber#46]
It seems we have received some incorrect German translations in https://github.com/jester-xbmc/skin.amber/commit/4ef93041a7219e1779b00536952fa7e1fca2b85d as "Low list" is now translated to "Recommended Concerts" and there are also others.

Report is here http://forum.kodi.tv/showthread.php?tid=251260&pid=2307857#pid2307857

**Comment by jester-xbmc** [comment]
I speak german, I'll have a look, although I think this needs to be reported to transifex

**Comment by joethepartylion** [comment]
Excellent, thank you.

**Comment by joethepartylion** [comment]
We also need to get the translation engine to talk to the Jarvis branch, it's only updating master at the moment.
