### ISSUE TITLE
2.2.6 is broken

### ISSUE THREAD

**Issue by joethepartylion** [jester-xbmc/skin.amber#55]
For those using vertical the update gives them no home menu. Fixed in #54

**Comment by jester-xbmc** [comment]
I'll push 2.2.7, is this fixed confirmed ? (can't test, traveling)

**Comment by joethepartylion** [comment]
Yes, just tested and it fixes the menu disappearing.

Sorry this happened,

**Comment by jester-xbmc** [comment]
Don't worry, it happens, we can test a lot but not all, most don't use vertical i guess.
thx
