### ISSUE TITLE
Unable to disable static vertical menu

### ISSUE THREAD

**Issue by andybotting** [jester-xbmc/skin.amber#58]
In 2.2.7, I've found that the vertical menu is always static, irrespective of the config setting.

I've had to roll back to 2.2.5, which fixes the issue for me.

**Comment by joethepartylion** [comment]
Hi, I have the fix and I'll submit a pull to jester soon, so hopefully fixed in the next release.

Thanks for the report.

**Comment by jester-xbmc** [comment]
fix pulled.
