### ISSUE TITLE
Feature request: Display episode title in PVR Guide and Recordings

### ISSUE THREAD

**Issue by bconway** [jester-xbmc/skin.amber#73]
With Estuary on the horizon as the new default, I'm checking out my options. Amber is great, but it appears that items in the PVR Guide and Recordings sections only show the show name and the description, not the episode title. Confluence shows the episode in both places. Can this be added?

I didn't check the main channel listing window, it may be absent there as well.

Thanks.

**Comment by joethepartylion** [comment]
Should be available in #79

**Comment by bconway** [comment]
Thanks! It looks good. I found one place that it doesn't show the episode title: the info panel (i) when viewing a recording or Live TV. Could it be added there? Screenshots attached. Thanks.

![screen shot 2017-02-23 at 10 08 50 am 2](https://cloud.githubusercontent.com/assets/630723/23267435/622d399a-f9b0-11e6-8d55-2e56eb93e2fa.png)

![screen shot 2017-02-23 at 10 09 28 am 2](https://cloud.githubusercontent.com/assets/630723/23267457/7256140e-f9b0-11e6-8e45-d0d5ebc397ed.png)
