### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by GnFlala** [jester-xbmc/skin.amber#77]
I am using this skin on kodi 17 and i am trying to make my life easy.

I would like to see

1. Movie information. Been able to see where the media is localy stored. Super helpful if a media is wrongly recognized by ypur scrapper and you want to refresh the info. We could see that in the v16 kodi amber skin on movies info page on the far down left side of screen.

2. Subtitles download dialog. Up to kodi version 16 we could see the actual file name. Now we see the name of the movie. Makes it harder to choose the right subtitles. 

3. Addons. We are not able to see what addons we have currently installed. The only way is to press on one addon and see if you see the install or uninstall button

4. Addons. We cannot see what addons we have enabled or disabled. Same as above we have to press on each one addon and see if we see the enable or disable button. Up to kodi 16 we could see on the page with addons next to the name if they are installed, enabled or disabled.

Thanks for this skin to all the devs working on it.

**Comment by joethepartylion** [comment]
Hi.

1. This is visible but not obvious, if you go up from the horizontal menu you can scroll down the list and location is in there. It may need to be moved if people use it a lot.

2. This has been added and should be in soon.

3. I'll take  a look

4. I'll take a look.

**Comment by joethepartylion** [comment]
Hopefully 2,3,4 are fixed in #79

**Comment by GnFlala** [comment]
Is it possible on subtitles download page to see more than just the name? Lets say also see season and episode? 
If it is an online link usually on the bottom we will see something that does not help. On the upper part after your changes we can now see the name of the episode. 
But when someone try to find subs what really helps is the show name then the season number and then the episode number. It would be nice if we still are able to see the episode name as is after your changes.
There is plenty of room up where you change it and it shows the name.

**Comment by joethepartylion** [comment]
Should be ok with #83

**Comment by jester-xbmc** [comment]
Thanks, closing, this will go into 3.0.7 later
