### ISSUE TITLE
Rss overlaps with now playing

### ISSUE THREAD

**Issue by GnFlala** [jester-xbmc/skin.amber#78]
if this is reported please discard.

Rss feeds on top left overlaps with now playing since now they are both on the same line.

maybe when the now playing line is there rss should go to the old place on the bottom left of the screen or now playing could be moved right under rss feeds since now playing is the new info and it does not stay always there.

I reopened since i saw that the other case is not the same.
Too tired and i false reading.

**Comment by joethepartylion** [comment]
This is fixed in my Krypton11 branch, I'll push to here soon.

**Comment by GnFlala** [comment]
Thanks then i am closing this.
