### ISSUE TITLE
Breaks Video Plugins

### ISSUE THREAD

**Issue by nioncode** [jester-xbmc/skin.amber#80]
For the past 2 hours I was debugging why my video plugin wasn't working anymore.
Turns out, it works just fine with the default kodi skin, but does not work with amber.

Same thing happens with the example video plugin from https://github.com/romanvm/plugin.video.example.
If you navigate to addons -> example kodi video plugin -> animals -> alligator, then nothing happens. Somehow, kodi does not start the video playback.

How can this be fixed?

**Comment by jester-xbmc** [comment]
Funny, I just notice the same thing for youtube and my other video plugins, if you select context menu and hit play it works.

@joethepartylion as i'm on a plane, can you have a look ? key assignment issue in Krypton ?

**Comment by joethepartylion** [comment]
I saw a message in the forum yesterday and have been having a look. I can get it to work sometimes which makes it harder to debug as there are no log messages or anything. 

I'm going to have to go back through git and try out a few versions to try and pin it down I think.

**Comment by nioncode** [comment]
Looks like this has never worked. I tried a few different versions from git, even went back to v2.0.15. None of them worked.
I never worked on a skin before, so I don't know where to look at all.

EDIT: only tested on krypton, though. This possibly worked with older versions of kodi.
EDIT2: version 2.2.5 works fine on Jarvis

**Comment by jester-xbmc** [comment]
I think something changed for Krypton implementation, I believe for Javis this was not issue...

**Comment by joethepartylion** [comment]
What platform are you running on?

**Comment by nioncode** [comment]
Linux (Archlinux)

**Comment by joethepartylion** [comment]
hmm, can you confirm if this version works for you

https://github.com/joethepartylion/skin.amber/tree/2d05b83444bd8b2c692eb0626ebae9485328939e

and if this doesn't

https://github.com/joethepartylion/skin.amber/tree/3c7c9ca31accacd7dc050fc47ee76b3459c8ac1e

If that is in fact the case, it is the new shelf layout breaking it...and that will be odd.

**Comment by nioncode** [comment]
None of them work. Does it work on your platform? Which platform is this?

**Comment by joethepartylion** [comment]
Hmm, can you try this

https://github.com/joethepartylion/skin.amber/tree/Krypton11

I wasn't specifying the addon type correctly for shelf addons and hopefully this fixes it, hence why it seemed sporadic. Launched via addon browser or addon windows it worked, launched via the shelf it didn't.

**Comment by nioncode** [comment]
Works fine, thanks :)

**Comment by joethepartylion** [comment]
Excellent, #81 on its way.

Thanks for the help.

**Comment by jester-xbmc** [comment]
Fixed and closed.
Thanks !
