### ISSUE TITLE
PVR Guide category colors are very low contrast and difficult to see at 10+ feet

### ISSUE THREAD

**Issue by bconway** [jester-xbmc/skin.amber#84]
I'm no designer and don't know if darkening things up would make it ugly. It's mostly the category that shows up as salmon(?) in Amber (blue in Confluence) that's the issue. Screenshots attached for comparison, thanks.

![screen shot 2017-02-23 at 10 07 09 am 2](https://cloud.githubusercontent.com/assets/630723/23267589/cd62e624-f9b0-11e6-9fd8-c2ca0ab43a23.png)

![screen shot 2017-02-23 at 10 06 49 am 2](https://cloud.githubusercontent.com/assets/630723/23267606/dbf882f2-f9b0-11e6-8fe3-652e160de46d.png)

**Comment by jester-xbmc** [comment]
Its probably because of the Pvr.jpg background image, i'll have a look.

**Comment by joethepartylion** [comment]
Does this look better?

https://github.com/jester-xbmc/skin.amber/pull/86/commits/90299a8cd4705f2216d2dd06bd24c9a587e817ac

**Comment by joethepartylion** [comment]
I think this was fixed in #86

**Comment by bconway** [comment]
Thanks!
